apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  # Replace the value below with your actual DATABASE_URL or keep this for local testing
  database_url: postgresql://postgres:password@postgres-service:5432/postgres
  POSTGRES_PASSWORD: password
